spring:
  config:
    activate:
      on-profile: default

  cloud:
    function:
      definition: source;uppercase;sink

    stream:
      bindings:
        uppercase-in-0:
          destination: source-out-0
        uppercase-out-0:
          destination: sink-in-0
      kafka:
        binder:
          brokers: localhost:9092

---
spring:
  config:
    activate:
      on-profile: test

  cloud:
    stream:
      kafka:
        binder:
          brokers: ${spring.embedded.kafka.brokers}