spring:
  config:
    activate:
      on-profile: default

  cloud:
    function:
      definition: source;uppercase;sink

    stream:
      bindings:
        uppercase-in-0:
          destination: source-out-0
        uppercase-out-0:
          destination: sink-in-0